
# cargo-vet config file

[cargo-vet]
version = "0.9"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.prio]
audit-as-crates-io = false
criteria = "safe-to-deploy"

[policy.prio-binaries]
criteria = "safe-to-run"

[[exemptions.aes]]
version = "0.8.2"
criteria = "safe-to-deploy"
notes = "This is only used when the \"crypto-dependencies\" feature is enabled."

[[exemptions.approx]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.az]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.bitvec]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.bytemuck]]
version = "1.12.1"
criteria = "safe-to-deploy"

[[exemptions.cipher]]
version = "0.4.3"
criteria = "safe-to-deploy"
notes = "This is only used when the \"crypto-dependencies\" or \"prio2\" features are enabled."

[[exemptions.cpufeatures]]
version = "0.2.5"
criteria = "safe-to-deploy"
notes = "This is only used when the \"crypto-dependencies\" or \"prio2\" features are enabled."

[[exemptions.criterion]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.2"
criteria = "safe-to-deploy"
notes = "This is only used when the \"multithreaded\" feature is enabled."

[[exemptions.crossbeam-epoch]]
version = "0.9.10"
criteria = "safe-to-deploy"
notes = "This is only used when the \"multithreaded\" feature is enabled."

[[exemptions.crossbeam-utils]]
version = "0.8.11"
criteria = "safe-to-deploy"
notes = "This is only used when the \"multithreaded\" feature is enabled."

[[exemptions.ctr]]
version = "0.9.2"
criteria = "safe-to-deploy"
notes = "This is only used when the \"crypto-dependencies\" feature is enabled."

[[exemptions.digest]]
version = "0.10.3"
criteria = "safe-to-deploy"
notes = "This is only used when the \"crypto-dependencies\" feature is enabled."

[[exemptions.fixed]]
version = "1.20.0"
criteria = "safe-to-deploy"

[[exemptions.fixed-macro-types]]
version = "1.2.0"
criteria = "safe-to-run"

[[exemptions.funty]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.6"
criteria = "safe-to-deploy"
notes = "This is only used when the \"crypto-dependencies\" or \"prio2\" features are enabled."

[[exemptions.getrandom]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.half]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-run"

[[exemptions.iai]]
version = "0.1.1"
criteria = "safe-to-run"

[[exemptions.matrixmultiply]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.memoffset]]
version = "0.6.5"
criteria = "safe-to-deploy"
notes = "This is only used when the \"multithreaded\" feature is enabled."

[[exemptions.nalgebra]]
version = "0.29.0"
criteria = "safe-to-run"

[[exemptions.nalgebra-macros]]
version = "0.1.0"
criteria = "safe-to-run"

[[exemptions.once_cell]]
version = "1.14.0"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.ppv-lite86]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error]]
version = "1.0.4"
criteria = "safe-to-run"

[[exemptions.radium]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_distr]]
version = "0.4.3"
criteria = "safe-to-run"

[[exemptions.safe_arch]]
version = "0.7.0"
criteria = "safe-to-run"

[[exemptions.sha2]]
version = "0.10.8"
criteria = "safe-to-deploy"
notes = "We do not use the new asm backend, either its feature or CPU architecture"

[[exemptions.simba]]
version = "0.6.0"
criteria = "safe-to-run"

[[exemptions.statrs]]
version = "0.16.0"
criteria = "safe-to-run"

[[exemptions.typenum]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.wide]]
version = "0.7.11"
criteria = "safe-to-run"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.wyz]]
version = "0.5.1"
criteria = "safe-to-deploy"
