
# cargo-vet config file

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.divviup]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.firefox]
url = "https://hg.mozilla.org/mozilla-central/raw-file/tip/supply-chain/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.prio]
audit-as-crates-io = false
criteria = "safe-to-deploy"

[policy.prio-binaries]
criteria = "safe-to-run"

[[exemptions.addr2line]]
version = "0.16.0"
criteria = "safe-to-run"

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-run"

[[exemptions.aead]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.aes]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.aes]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.aes-gcm]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.ansi_term]]
version = "0.12.1"
criteria = "safe-to-run"

[[exemptions.autocfg]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.61"
criteria = "safe-to-run"

[[exemptions.bitflags]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.bumpalo]]
version = "3.6.1"
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "1.4.3"
criteria = "safe-to-deploy"

[[exemptions.cast]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.cc]]
version = "1.0.67"
criteria = "safe-to-deploy"

[[exemptions.cipher]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "2.34.0"
criteria = "safe-to-run"

[[exemptions.clap]]
version = "3.2.20"
criteria = "safe-to-run"

[[exemptions.clap_lex]]
version = "0.2.4"
criteria = "safe-to-run"

[[exemptions.color-eyre]]
version = "0.6.2"
criteria = "safe-to-run"

[[exemptions.color-spantrace]]
version = "0.2.0"
criteria = "safe-to-run"

[[exemptions.cpufeatures]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.crossbeam-channel]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-deque]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.ctr]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.ctr]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.eyre]]
version = "0.6.5"
criteria = "safe-to-run"

[[exemptions.generic-array]]
version = "0.14.4"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.ghash]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.25.0"
criteria = "safe-to-run"

[[exemptions.half]]
version = "1.7.1"
criteria = "safe-to-run"

[[exemptions.heck]]
version = "0.3.3"
criteria = "safe-to-run"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-deploy"

[[exemptions.indenter]]
version = "0.3.3"
criteria = "safe-to-run"

[[exemptions.indexmap]]
version = "1.9.1"
criteria = "safe-to-run"

[[exemptions.inout]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.10.5"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.51"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.121"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.14"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.4.1"
criteria = "safe-to-run"

[[exemptions.memoffset]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.4.4"
criteria = "safe-to-run"

[[exemptions.num-integer]]
version = "0.1.44"
criteria = "safe-to-run"

[[exemptions.num-traits]]
version = "0.2.14"
criteria = "safe-to-run"

[[exemptions.num_cpus]]
version = "1.13.0"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.26.2"
criteria = "safe-to-run"

[[exemptions.once_cell]]
version = "1.7.2"
criteria = "safe-to-deploy"

[[exemptions.oorandom]]
version = "11.1.3"
criteria = "safe-to-run"

[[exemptions.os_str_bytes]]
version = "6.3.0"
criteria = "safe-to-run"

[[exemptions.owo-colors]]
version = "3.2.0"
criteria = "safe-to-run"

[[exemptions.pin-project-lite]]
version = "0.2.7"
criteria = "safe-to-run"

[[exemptions.plotters]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.2"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.polyval]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.10"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error]]
version = "1.0.4"
criteria = "safe-to-run"

[[exemptions.quote]]
version = "1.0.9"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.5.6"
criteria = "safe-to-run"

[[exemptions.regex-syntax]]
version = "0.6.26"
criteria = "safe-to-run"

[[exemptions.ring]]
version = "0.16.20"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.5"
criteria = "safe-to-deploy"

[[exemptions.same-file]]
version = "1.0.6"
criteria = "safe-to-run"

[[exemptions.scopeguard]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.152"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.152"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.91"
criteria = "safe-to-deploy"

[[exemptions.sharded-slab]]
version = "0.1.3"
criteria = "safe-to-run"

[[exemptions.spin]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.static_assertions]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.8.0"
criteria = "safe-to-run"

[[exemptions.structopt]]
version = "0.3.26"
criteria = "safe-to-run"

[[exemptions.structopt-derive]]
version = "0.4.18"
criteria = "safe-to-run"

[[exemptions.subtle]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.104"
criteria = "safe-to-deploy"

[[exemptions.textwrap]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.textwrap]]
version = "0.15.0"
criteria = "safe-to-run"

[[exemptions.thiserror]]
version = "1.0.38"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.38"
criteria = "safe-to-deploy"

[[exemptions.thread_local]]
version = "1.1.4"
criteria = "safe-to-run"

[[exemptions.tinytemplate]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.tracing]]
version = "0.1.28"
criteria = "safe-to-run"

[[exemptions.tracing-core]]
version = "0.1.21"
criteria = "safe-to-run"

[[exemptions.tracing-error]]
version = "0.2.0"
criteria = "safe-to-run"

[[exemptions.tracing-subscriber]]
version = "0.3.6"
criteria = "safe-to-run"

[[exemptions.typenum]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.5"
criteria = "safe-to-deploy"

[[exemptions.unicode-segmentation]]
version = "1.8.0"
criteria = "safe-to-run"

[[exemptions.unicode-width]]
version = "0.1.8"
criteria = "safe-to-run"

[[exemptions.universal-hash]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.vec_map]]
version = "0.8.2"
criteria = "safe-to-run"

[[exemptions.version_check]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.walkdir]]
version = "2.3.2"
criteria = "safe-to-run"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.74"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.74"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.74"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.74"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.74"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.51"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.5"
criteria = "safe-to-run"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

