[package]
name = "prio-binaries"
version = "0.5.0"
edition = "2018"
description = "Prio utilities"
license = "MPL-2.0"
repository = "https://github.com/divviup/libprio-rs"

[dependencies]
base64 = "0.22.1"
fixed = "1.28"
rand = "0.9"
prio = { path = "..", features = ["experimental", "test-util"] }
