name: supply-chain

on:
  push:
    branches:
     - main
     - release/**
  pull_request:
    branches:
     - main
     - release/**
  workflow_dispatch:

jobs:
  vet:
    name: Vet Dependencies
    runs-on: ubuntu-latest
    env:
      CARGO_VET_COMMIT: 8b40d6351ed9758a73a4a0bf2c930c17a35c5e15
    steps:
    - uses: actions/checkout@v6
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Cache cargo vet
      uses: actions/cache@v5
      with:
        path: ${{ runner.tool_cache }}/cargo-vet
        key: cargo-vet-bin-${{ env.CARGO_VET_COMMIT }}
    - name: Add the tool cache directory to the search path
      run: echo "${{ runner.tool_cache }}/cargo-vet/bin/" >> $GITHUB_PATH
    - name: Ensure that the tool cache is populated with the cargo-vet binary
      run: cargo install --root ${{ runner.tool_cache }}/cargo-vet --git https://github.com/mozilla/cargo-vet.git --rev ${{ env.CARGO_VET_COMMIT }} --locked cargo-vet
    - name: Invoke cargo-vet
      run: cargo vet --locked
